### ISSUE TITLE
Multiple cache times

### ISSUE THREAD

**Issue by hursey013** [gilbitron/PHP-SimpleCache#4]
Thanks for creating this, it's very helpful.  Is there any way to change the cache time depending on whats being cached.  For example, I may want to cache one object for and hour, and something else for a day - or is this just meant to have one global cache time that is applied to everything?

**Comment by csprance** [comment]
You can do something like this.
```php
$cache1 = new Gilbitron\Util\SimpleCache();
$cache1->cache_path = 'cachesmall/';
$cache1->cache_time = 60;

$cache2 = new Gilbitron\Util\SimpleCache();
$cache2->cache_path = 'cachesmall/';
$cache2->cache_time = 60;

if (cacheType == 'large') {
  $cache->set_cache('largecache', $data);
}
if (cacheType == 'small') {
  $cache->set_cache('smallcache', $data);
}
                  


```

**Comment by hursey013** [comment]
Makes sense - thank you!
