### ISSUE TITLE
how to set to so cache never expires?

### ISSUE THREAD

**Issue by sk29110** [gilbitron/PHP-SimpleCache#7]
I was wondering if there is any way to set so the cache never expires?

**Comment by gilbitron** [comment]
I'm afraid that's not possible at the moment. You could just save the data to a file in that case?

**Comment by sk29110** [comment]
What you mean by save the data to a file? The cache is saved in a file right? I think I can just remove the line where you remove the cache when the time is about to expired?

**Comment by gilbitron** [comment]
You could. Or you could just use `file_put_contents` and `file_get_contents` manually. No need for this library.

**Comment by sk29110** [comment]
Thanks
